environment:
  matrix:
    - lang: cpp

install:
 - "cd cpp"
 - "thirdparty\\win_download_and_build.cmd"
 - "win_develop_env.cmd"
 - "mkdir release-build"
 - "cd release-build"

build_script:
 - cmake -G "Visual Studio 14 Win64" ..
 - cmake --build . --config Release"

test_script:
 - "ctest"
